<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Thruway' => array($vendorDir . '/voryx/thruway/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Hybrid' => array($vendorDir . '/hybridauth/hybridauth/hybridauth'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'GifCreator' => array($vendorDir . '/sybio/gif-creator/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
);
